<?php
session_start();
require_once '../php/database.php';

// Vérification de la session
if (!isset($_SESSION['user_role']) || $_SESSION['user_role'] !== 'teacher') {
    header('Location: ../index.php?role=teacher');
    exit();
}

$user_id = $_SESSION['user_id'];
$teacher_id = null;
$assigned_subjects = [];
$assigned_classes = [];

try {
    // Get teacher's ID
    $stmt_teacher_id = $pdo->prepare("SELECT id FROM enseignants WHERE id_user = :user_id");
    $stmt_teacher_id->bindParam(':user_id', $user_id);
    $stmt_teacher_id->execute();
    $teacher_id = $stmt_teacher_id->fetchColumn();

    if (!$teacher_id) {
        $_SESSION['error'] = "Vos informations d'enseignant n'ont pas été trouvées.";
        header('Location: ../php/logout.php');
        exit();
    }

    // Get subjects assigned to this teacher
    $stmt_subjects = $pdo->prepare("SELECT m.id, m.nom_matiere FROM matieres m JOIN enseignant_matiere em ON m.id = em.id_matiere WHERE em.id_enseignant = :teacher_id ORDER BY m.nom_matiere");
    $stmt_subjects->bindParam(':teacher_id', $teacher_id);
    $stmt_subjects->execute();
    $assigned_subjects = $stmt_subjects->fetchAll();

    // Get classes that have students taking subjects taught by this teacher
    $stmt_all_classes = $pdo->query("SELECT id, nom_classe FROM classes ORDER BY nom_classe");
    $assigned_classes = $stmt_all_classes->fetchAll();

} catch (PDOException $e) {
    $_SESSION['error'] = "Erreur de chargement des données : " . $e->getMessage();
}

?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Ajouter une Note</title>
    <link rel="stylesheet" href="../css/dashboard.css">
    <link rel="stylesheet" href="../css/teacher-dashboard.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        body {
            background: #f5f6fa;
            margin: 0;
        }
        .main-content {
            padding: 2rem;
        }
    </style>
</head>
<body>
    <div class="dashboard-container">
        <aside class="sidebar">
            <div class="sidebar-header">
                <img src="../images/logo_keyce.JPEG" alt="Logo Keyce" class="logo" />
                <h2>Espace Enseignant</h2>
            </div>
            <nav class="sidebar-nav">
                <a href="dashboard.php" class="nav-item"><i class="fas fa-home"></i> Tableau de bord</a>
                <a href="add-note.php" class="nav-item active"><i class="fas fa-graduation-cap"></i> Gestion des notes</a>
                <a href="notifications.php" class="nav-item"><i class="fas fa-bell"></i> Notifications</a>
                <a href="profile.php" class="nav-item"><i class="fas fa-user-circle"></i> Profil</a>
            </nav>
            <div class="sidebar-footer">
                <a href="../php/logout.php"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            </div>
        </aside>
        <main class="main-content">
            <div class="header">
                <h1>Ajouter une Note</h1>
            </div>
            <div class="info-card">
                <?php if (isset(
                    $_SESSION['success'])): ?>
                    <div class="message message-success">
                        <?php echo htmlspecialchars($_SESSION['success']); unset($_SESSION['success']); ?>
                    </div>
                <?php endif; ?>
                <?php if (isset($_SESSION['error'])): ?>
                    <div class="message message-error">
                        <?php echo htmlspecialchars($_SESSION['error']); unset($_SESSION['error']); ?>
                    </div>
                <?php endif; ?>
                <form class="add-note-form" id="addNoteForm" method="POST" action="../php/save_notes.php">
                    <div class="form-group">
                        <label for="student">Étudiant</label>
                        <select name="student" id="student" required>
                            <!-- Options dynamically generated by PHP -->
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="subject">Matière</label>
                        <select name="subject" id="subject" required>
                            <!-- Options dynamically generated by PHP -->
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="note">Note</label>
                        <input type="number" name="note" id="note" min="0" max="20" step="0.01" required />
                    </div>
                    <div class="form-group">
                        <label for="comment">Commentaire</label>
                        <textarea name="comment" id="comment" rows="3"></textarea>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn-primary"><i class="fas fa-save"></i> Enregistrer</button>
                    </div>
                </form>
            </div>
        </main>
    </div>
    <script src="../js/teacher.js"></script>
</body>
</html>
